name: CI

on: [push]

jobs:
  build-deb:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/truenas/middleware:master

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dev environment
        run: /usr/bin/install-dev-tools

      - name: Install Dependencies
        run: apt update && apt install -y debhelper-compat devscripts dh-python

      - name: Build deb package
        run: >
          dpkg-buildpackage
          -B
          --no-sign
          -jauto

      - name: Create artifacts dir
        run: mkdir artifacts
        if: success()

      - name: Move artifacts
        run: mv ../*.deb artifacts
        if: success()

      - uses: actions/upload-artifact@v4
        with:
          name: python3-ixdiagnose
          path: artifacts
        if: success()
